Refactor - Bump to 0.27
OpenSourcePolitics/decidim-module-question_captcha pull request #40
Opened 2023-07-13 11:08 UTC by AyakorK

This PR was initially made to bump the module but as it already exists I just updated few things

- Fix the issue of the rakefile
- Bump Ruby Version
- Refactor as it is done on the main

2023-07-13 13:30 UTC, paulinebessoles requested changes
Thank you @AyakorK ! Could you just make sure that this module will be compatible with all decidim-core patched versions? 🙏 
`decidim-core (~> 0.27)`

2023-07-13 14:20 UTC, AyakorK commented
It took quite a while because of my gemfile.lock that has deleted something it shouldn't have, but it is fixed !

2023-07-13 15:03 UTC, paulinebessoles approved these changes

2023-07-18 11:31 UTC, eliegaboriau approved these changes

2023-07-18 11:31 UTC, merged